const OK = 200;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER = 500;
const UNPROCESSABLE = 422;
const UNAUTHORIZED = 401;
const BAD_GATEWAY = 502;
const NO_CONTENT = 204;
const CREATED = 201;
const FORBIDDEN = 403;

export default {
  OK,
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER,
  UNPROCESSABLE,
  UNAUTHORIZED,
  BAD_GATEWAY,
  NO_CONTENT,
  CREATED,
  FORBIDDEN,
};
